version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.3
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Make
          command: |
            python3 -m venv venv
            . venv/bin/activate && make install
      - run:
          name: Lint with pylint and hadolint
          command: . venv/bin/activate && make lint
          
  push-docker:
    docker:  
      - image: docker:circleci/docker@2.1.2
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: capstone
          tag: "latest"
      - docker/push:
          image: capstone
          tag: "latest"          
          
  DeployDocker:
    docker:  
      - image: cimg/base:2022.06
    steps:
      - checkout
      - run:
          name: Install Minikube
          command: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && sudo install minikube-linux-amd64 /usr/local/bin/minikube
      - run:
          name: start Minikube
          command: minikube start && kubectl get po -A
      - run: 
          name: DeployDocker
          command: kubectl create deployment hello-minikube --image=kicbase/echo-server:1.0 && kubectl expose deployment hello-minikube --type=NodePort --port=8000
      - run:
          name: GetKube
          command: kubectl get services hello-minikube && kubectl port-forward service/hello-minikube 80:8000
          
  CheckConnection: 
    docker:  
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - run:
          name: Check connection
          command: curl localhost:8000
      
workflows:
  WFlow: 
    jobs:
      - build-and-test 
      - push-docker:
          requires: [build-and-test]
      - DeployDocker:
          requires: [build-and-test]
      - CheckConnection:
          requires: [DeployDocker]
