version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.3
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Make
          command: make all
          
  DeployDocker:
    docker: 
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - run:
          name: Build Docker
          command: docker build -t capstone . &&\ 
          docker tag capstone:latest 018538312056.dkr.ecr.us-east-1.amazonaws.com/capstone:latest &&\
          docker push 018538312056.dkr.ecr.us-east-1.amazonaws.com/capstone:latest

workflows:
  WFlow: 
    jobs:
      - build-and-test 
      - DeployDocker:
          requires: [build-and-test]
