version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.3
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Make
          command: |
            python3 -m venv venv
            . venv/bin/activate && make install
      - run:
          name: Lint with pylint and hadolint
          command: . venv/bin/activate && make lint
          
  DeployDocker:
    docker:  
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Tag and Push Docker
          command: chmod 755 run_docker.sh && ./run_docker.sh
          
  Kubes:
    docker:  
      - image: circleci/python@1.5.0
    steps:
      - checkout
      - run:
          name: run kubernetes
          command: ./run_kubernetes.sh
          
  CheckConnection: 
    docker:  
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - run:
          name: Check connection
          command: curl localhost:8000
          
  Cleanup: 
    docker:  
      - image: cimg/base:2022.06
    steps:
      - checkout
      - run:
          name: Cleanup
          command: docker system prune -f
      
workflows:
  WFlow: 
    jobs:
      - build-and-test 
      - DeployDocker:
          requires: [build-and-test]
      - Kubes:
          requires: [DeployDocker]
      - CheckConnection:
          requires: [Kubes]
      - Cleanup:
          requires: [CheckConnection]
