version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.3
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Make
          command: make all
          
  DeployDocker:
    docker:
      - image: cimg/python:3.11.3
    steps:
      - checkout
      - run:
          name: Build Docker
          command: echo "Hi"

workflows:
  WFlow: 
    jobs:
      - build-and-test 
      - DeployDocker:
          requires: [build-and-test]
